version: "3.9"

services:
  backend:
    build: ./memoriae-back
    container_name: memoriae-back
    ports:
      - "8080:8080"
    networks:
      - memoriae-network

  frontend:
    build: ./memoriae-front
    container_name: memoriae-front
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - memoriae-network

networks:
  memoriae-network:
    driver: bridge